name := "PhaseScanner"
version := "0.1.0"
scalaVersion := "2.12.8"
organization := "com.hydra"
libraryDependencies += "com.hydra" %% "sydra" % "0.6.0"
libraryDependencies += "org.pegdown" % "pegdown" % "1.6.0"
libraryDependencies += "com.hwaipy" %% "hydrogen" % "0.3.0"
libraryDependencies += "org.scalafx" %% "scalafx" % "11-R16"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.5" % "test"
libraryDependencies += "com.xeiam.xchart" % "xchart" % "2.5.1" exclude("de.erichseifert.vectorgraphics2d", "VectorGraphics2D")
libraryDependencies += "org.python" % "jython" % "2.7.0"
scalacOptions ++= Seq("-feature")
scalacOptions ++= Seq("-deprecation")
scalacOptions ++= Seq("-Xlint")
fork := true
