name := "hydralocal"
version := "0.1.0"
scalaVersion := "2.12.4"
organization := "com.hydra"
libraryDependencies += "com.hydra" %% "sydra" % "0.6.0"
libraryDependencies += "org.pegdown" % "pegdown" % "1.6.0"
libraryDependencies += "com.hwaipy" %% "hydrogen" % "0.3.0"
libraryDependencies += "org.scalafx" %% "scalafx" % "8.0.102-R11"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"
fork := true
scalacOptions ++= Seq("-feature")
scalacOptions ++= Seq("-deprecation")